#!/usr/bin/env python

# This script attempts to extract the original URL from an
# Apple News URL and copy it to your clipboard.
# This script was tested in Python 3.7 and Pythonista's Python 3.6

import requests
from sys import argv
from bs4 import BeautifulSoup as bs


def get_redirect_link(url):
    if url == None:
        url = input("URL> ")
    
    response = requests.get(url)
    data = response.text
    
    try:
        soup = bs(data, "html5lib")
    except:
        soup = bs(data, "html.parser")
    
    for link in soup.find_all('a'):
        try:
            if 'click here' in link.text.lower():
                return(link.get('href'))
            print(link)
        except:
            if '-v' in argv:
                print(link)
                print(link.text)
                print(type(link))
            exit()
    
    if '-v' in argv:
        print(data)
    
    print('no click here found')
    
    exit()

try:
    import appex
    import clipboard
    import webbrowser
    
    if appex.is_running_extension():
        url = appex.get_url()
    else:
        url = None
    
    link = get_redirect_link(url)
    
    clipboard.set(link)
    
    webbrowser.open('safari-'+link, new=2)
except:
    import subprocess
    link = get_redirect_link(None)
    
    print(link)
    
    # copy to the clipboard
    # using pbcopy as not all Python 3 installs will have access
    # to AppKit depending on how it's installed.
    task = subprocess.Popen(
        ['/usr/bin/pbcopy'],
        env={'LANG': 'en_US.UTF-8'},
        stdin=subprocess.PIPE
    )
    task.communicate(link.encode('utf-8'))
