#!/usr/bin/python
import os
import subprocess
from sys import argv

def print_help():
    print("")
    print("This utility converts ICNS files to PNG.")
    print("Usage: icp [-f] [file path]")
    print("Example: icp -f /Users/bryan/Desktop/1Password.icns")
    print("Options:")
    print("\t-f\tSkips ICNS file check and forces the conversion to PNG.")
    print("\t-h\tPrints this help document.")
    print("")
    exit()

if '-h' in argv or '--help' in argv or len(argv) == 1:
    print_help()

# get icns input, setup output path
try:
    icns_path = argv[-1]
    root, ext = os.path.splitext(icns_path)
    out_path = root + ".png"
except IndexError:
    print_help()

# verifies if the file exists
if not os.path.exists(icns_path):
    print("\nFile not found.")
    print_help()

# skips ICNS file check if -f is in the arguments
if '-f' not in argv:
    # read the input file, verify it's an icns file
    file = open(icns_path, 'r')
    data = file.readlines()
    file.close()
    if 'icns' not in data[0]:
        print("\nThe supplied file doesn't appear to be an ICNS file.")
        print_help()

# convert the icns file to png
cmd = ['sips', '-s', 'format', 'png', icns_path, '--out', out_path]
task = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
out, err = task.communicate()
if err:
    print("Errors:\n\t{0}".format(err.strip()))
