#!/usr/bin/python
import os
import subprocess
from sys import argv


try:
    script, path = argv
except:
    print("Renames script to postflight and makes it executable.")
    print("Usage: pf /path/to/script.py")
    exit(0)


base_path = os.path.dirname(path)
pf_path = os.path.join(base_path, 'postflight')
cmd = ['/bin/chmod', '+x', pf_path]

os.rename(path, pf_path)
subprocess.call(cmd)
