#!/usr/bin/python
import subprocess
from sys import argv

pts = "20" # packets to send
host = "google.com"
ps = 0 # total packets sent
pr = 0 # total packets received

def switch(item):
    index = argv.index(item) + 1
    return(argv[index])


def core(pts, host):
    global ps
    global pr
    
    cmd = ["ping", "-c", pts, host]

    task = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = task.communicate()

    ping_results = out.split("\n")[-3:]

    packets = ping_results[0]
    latency = ping_results[1]
    
    try:
        packets_received = packets.split(" ")[3]
        packets_lost_percent = packets.split(" ")[6]
        latency_speeds = latency.split(" ")[3]
        latency_average = latency_speeds.split('/')[1]
    except IndexError:
        packets = ping_results[1].split(' ')
        packets_received = packets[3]
        packets_lost_percent = packets[6]
        latency_average = "N/A"

    print("")
    print("{0}/{1} packets received".format(packets_received, pts))
    print("{0} packet loss".format(packets_lost_percent))
    print("{0}ms latency".format(latency_average))
    print("")
    
    ps += int(pts)
    pr += int(packets_received)


if "-p" in argv:
    pts = switch("-p")
if "--packets" in argv:
    pts = switch("--packets")
if "-h" in argv:
    host = switch("-h")
if "--host" in argv:
    host = switch("--host")

try:
    if "--loop" in argv:
        while True:
            core(pts, host)
    else:
        core(pts, host)
except KeyboardInterrupt:
    print("")
    print("total packets sent/received:")
    print("\t{0}/{1}".format(pr, ps))
    print("")
    exit(0)

# add a part when canceling that adds up how many pings have been done, and packets dropped
# total packets sent/dropped, total percent.
# write to a tiny json file 
