#!/usr/bin/python
import logging
import subprocess
from sys import argv
from time import sleep

pts = "20" # packets to send
host = "google.com"
ps = 0 # total packets sent
pr = 0 # total packets received

cmd = '/usr/bin/stat -f "%Su" /dev/console'.split(' ')
output = subprocess.Popen(cmd, stdout=subprocess.PIPE)
user = output.stdout.read().strip()
user = user.replace('"', '')

logging.basicConfig(filename='/Users/{0}/Library/Logs/ping_test.log'.format(user),\
    level=logging.INFO,\
    format='%(asctime)s - %(levelname)s -  %(message)s',\
    datefmt='%Y-%m-%d %I:%M:%S %p')

def switch(item):
    index = argv.index(item) + 1
    return(argv[index])


def core(pts, host):
    global ps
    global pr
    
    cmd = ["ping", "-c", pts, host]
    
    task = subprocess.Popen(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    out, err = task.communicate()
    
    ping_results = out.split("\n")[-3:]
    
    try:
        packets = ping_results[0]
        latency = ping_results[1]
    except:
        if "cannot resolve" in err:
            print("cannot resolve host")
            logging.info("cannot resolve host")
            sleep(5)
            return
        print("output:")
        print(out)
        print("")
        print("errors:")
        print(err)
        print("")
        exit(1)
    
    try:
        packets_received = packets.split(" ")[3]
        packets_lost_percent = packets.split(" ")[6]
        latency_speeds = latency.split(" ")[3]
        latency_average = latency_speeds.split('/')[1]
    except IndexError:
        packets = ping_results[1].split(' ')
        packets_received = packets[3]
        packets_lost_percent = packets[6]
        latency_average = "N/A"
    
    info = """{0}/{1} packets received
{2} packet loss
{3}ms latency""".format(packets_received, pts,packets_lost_percent, latency_average)
    
    print("")
    print(info)
    print("")
    
    logging.info(info)
    
    ps += int(pts)
    pr += int(packets_received)


if "-p" in argv:
    pts = switch("-p")
if "--packets" in argv:
    pts = switch("--packets")
if "-h" in argv:
    host = switch("-h")
if "--host" in argv:
    host = switch("--host")

try:
    if "--loop" in argv:
        while True:
            core(pts, host)
    else:
        core(pts, host)
except KeyboardInterrupt:
    print("")
    print("total packets sent/received:\n\t{0}/{1}".format(pr, ps))
    print("")
    logging.info("total packets sent/received:\n\t{0}/{1}".format(pr, ps))
    exit(0)