#!/usr/bin/env python3
import yaml
import pathlib
from sys import argv
from pprint import pprint

#
# this script attempts to quickly validate YAML
#

try:
    path = pathlib.Path(argv[1])
except IndexError:
    print("\nPlease input a path to a YAML file as argument 1.\n")
    exit(1)

if path.is_file() is False:
    print("\nInvalid file. Please input a YAML file path as argument 1.\n")
    exit(1)

with open(path, 'r') as file:
    try:
        yaml_data = yaml.safe_load(file)
    except yaml.parser.ParserError as e:
        print(f"\nInvalid YAML data:\n{e}")
        exit(1)
    pprint(yaml_data)
    print("\nThe YAML data appears valid.")
